imports:
    - { resource: services/repositories.yaml }
    - { resource: services/parameters.yaml }
    - { resource: services/security.yaml }
    - { resource: services/event-subscribers.yaml }
    - { resource: services/controllers.yaml }
    - { resource: services/admin_controllers.yaml }
    - { resource: services/validators.yaml }
    - { resource: services/cli.yaml }

services:

    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # ALIASES
    app.user_factory: '@App\Service\UserFactory'
    app.complex_user_password_encoder: '@App\Service\ComplexUserPasswordEncoder'
    app.user_registration_service: '@App\Service\UserRegistrationService'
    app.user_authentication_service: '@App\Service\UserAuthenticationService'
    app.user_role_manager: '@App\Service\UserRoleManager'

    # SERVICE DEFINITIONS
    App\Service\UserFactory:
        arguments: [ '@app.complex_user_password_encoder' ]

    App\Service\ComplexUserPasswordEncoder:
        arguments: [ '%app.password_cost%', '%app.password_pass_phrase%' ]

    App\Service\UserRegistrationService:
        arguments: [ '@app.user_repository', '@app.user_factory', '@event_dispatcher' ]

    App\Service\UserAuthenticationService:
        arguments: [ '@app.complex_user_password_encoder' ]

    App\Service\UserRoleManager: ~