imports:
    - { resource: services/repositories.yaml }
    - { resource: services/parameters.yaml }

services:

    # ALIASES
    app.user_factory: '@App\Service\UserFactory'
    app.complex_user_password_encoder: '@App\Service\ComplexUserPasswordEncoder'
    app.user_registration_service: '@App\Service\UserRegistrationService'

    # SERVICE DEFINITIONS
    App\Service\UserFactory:
        arguments: [ '@app.complex_user_password_encoder' ]

    App\Service\ComplexUserPasswordEncoder:
        arguments: [ '%app.password_cost%', '%app.password_pass_phrase%' ]

    App\Service\UserRegistrationService:
        arguments: [ '@app.user_repository', '@app.user_factory' ]