<?php

namespace App\Event;

class BalanceOperationEvents
{
    const BALANCE_OPERATION_CREATED = 'BALANCE_OPERATION_CREATED';
    const BALANCE_OPERATION_UPDATED = 'BALANCE_OPERATION_UPDATED';
    const BALANCE_OPERATION_DELETED = 'BALANCE_OPERATION_DELETED';
}